services:
  - type: web
    name: pastel1n
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DATABASE_URL
        fromDatabase:
          name: pastel1n-db
          property: connectionString

databases:
  - name: pastel1n-db
    plan: free
